namespace Easy_Language_Changer
{
    partial class Form1
    {
        /// <summary>
        /// Design variable needed.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up resources in use.
        /// </summary>
        /// <param name="disposing">has value true if the managed resources are to be deleted, false otherwise.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Code generated by Windows Form Design

        /// <summary>
        /// Method required for design window support. Do not modify
        /// the contents of the method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Text = "Form1";
        }

        #endregion
    }
}

